### ISSUE TITLE
transExceptions.py not included in repo

### ISSUE THREAD

**Issue by thingywhat** [sprpgs/PotionWars#52]
Yo~!

When attempting to run PotionWars.py, I got an error complaining about not being able to import "`transExceptions`":
```
thingywhat@Dee:~/git/PotionWars $ ./PotionWars.py 
/home/thingywhat/git/PotionWars/townmode.py:758: SyntaxWarning: name 'previousMode' is assigned to before global declaration
  global showTitleScreen, previousMode
/home/thingywhat/git/PotionWars/townmode.py:837: SyntaxWarning: name 'loadName' is assigned to before global declaration
  global loadName
/home/thingywhat/git/PotionWars/combat.py:96: SyntaxWarning: name 'enemies' is used prior to global declaration
  global allies, enemies, actionsInflicted, actionsEndured, activeAlly, chosenActions, initialAllies, initialEnemies
Traceback (most recent call last):
  File "./PotionWars.py", line 27, in <module>
    import episode2
  File "/home/thingywhat/git/PotionWars/episode2.py", line 14, in <module>
    import transExceptions
ImportError: No module named transExceptions
thingywhat@Dee:~/git/PotionWars $
```
A bit of checking revealed that the file does not exist in the Git repo..!

So, after a quick grep, I noticed [this line](https://github.com/sprpgs/PotionWars/blob/0bc3493475a23a12167eeff7c5ff5f8fa69d1d0e/.gitignore#L96) in your .gitignore... Which is probably the reason it is not committed.

Actually, that .gitignore is pretty big -- in case you don't know, you can use wildcards in that file to do nifty things like ignore all `.pyc` files you generate in your repo folder. (A line with "*.pyc" would do the trick.)

**Comment by sprpgs** [comment]
I don't know why my .gitignore is so big. I certainly didn't build it manually! I was probably just copying and pasting some git code from stackoverflow somewhere that I didn't really understand at the time. Plus I don't even really use it...I always explicitly add files when committing (I rarely have more than four or five files to change in any one commit).

Anyway, I've pushed a few version with transExceptions in it. Thanks for looking at my code! It's a horrible, nightmarish thing and I apologize for that. This is the first large project I've ever done so I don't really know what I'm doing.

**Comment by thingywhat** [comment]
Hey, no worries.
We all gotta start somewhere..!

>I always explicitly add files when committing (I rarely have more than four or five files to change in any one commit).
Ah, small commits are good practice. Kudos..!
I like making my commits really small, usually one for every complete change to something in the code, even if the change is small. That way reverts and cherry-picks can be done very accurately, and `git blame` becomes super-handy... The log also becomes more detailed naturally.

Anywho, the file is included, which was the original scope of this bug; so I guess that solves it. I'll report back if I find anything else.

Thanks.
